2020/11/15 19:54:04 [crit] 7#7: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.18.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 19:54:04 [error] 7#7: *1 open() "/var/www/html/public/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: site.local, request: "GET /favicon.ico HTTP/1.1", host: "site.local", referrer: "http://site.local/"
2020/11/15 19:55:30 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.19.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 19:56:16 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.20.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 20:00:08 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 20:00:09 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.21.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 20:02:11 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.22.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 20:02:44 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.22.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 20:04:31 [crit] 6#6: *4 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.22.0.1, server: site.local, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/15 15:09:38 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.24.0.1, server: site.local, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/17 16:23:44 [error] 28#28: *2 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "site.local", referrer: "http://site.local/"
2020/11/17 16:34:27 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (2: No such file or directory) while connecting to upstream, client: 172.25.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/17 16:35:22 [crit] 6#6: *1 connect() to unix:/sock/docker.sock failed (13: Permission denied) while connecting to upstream, client: 172.27.0.1, server: site.local, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/sock/docker.sock:", host: "site.local"
2020/11/17 16:37:50 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2020/11/17 16:37:50 [emerg] 1#1: mkdir() "/var/lib/nginx/body" failed (13: Permission denied)
2020/11/17 16:38:10 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2020/11/17 16:38:10 [emerg] 1#1: mkdir() "/var/lib/nginx/body" failed (13: Permission denied)
2020/11/17 16:39:49 [emerg] 1#1: open() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/17 16:41:03 [emerg] 1#1: open() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/17 16:41:45 [emerg] 1#1: open() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/17 17:01:27 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020/11/17 17:07:20 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020/11/17 17:08:43 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020/11/17 17:09:53 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020/11/17 17:12:27 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/17 17:12:46 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/17 17:12:51 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020/11/17 17:14:54 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/17 17:14:58 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
2020/11/17 17:27:39 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/18 18:24:01 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/18 18:24:15 [error] 27#27: *1 open() "/var/www/html/public/favicon.ico" failed (2: No such file or directory), client: 172.18.0.1, server: site.local, request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2020/11/18 18:25:39 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
2020/11/18 18:28:25 [alert] 1#1: unlink() "/var/run/nginx.pid" failed (13: Permission denied)
